// The GlobeTrotter catalog. There are no external travel APIs in this app — this
// file IS the data source behind City Search, Activity Search, recommendations
// and every cost estimate. 31 cities across 7 regions, 10 activities each.
//
// costIndex  1-100, relative daily cost of being in the city (Hanoi 22, Zurich-tier 90+)
// popularity 0-100, drives the default sort and the dashboard recommendations
// cost       USD per person
import type { ActivityCategory } from "@prisma/client";

/** [name, category, cost USD, durationHours, description] */
export type ActivitySeed = [string, ActivityCategory, number, number, string];

export type CitySeed = {
  name: string;
  country: string;
  region: string;
  costIndex: number;
  popularity: number;
  description: string;
  activities: ActivitySeed[];
};

export const CATALOG: CitySeed[] = [
  // ─────────────────────────── Europe ───────────────────────────
  {
    name: "Paris",
    country: "France",
    region: "Europe",
    costIndex: 82,
    popularity: 98,
    description: "Boulevards, world-class museums and a café on every corner.",
    activities: [
      ["Eiffel Tower Summit Access", "SIGHTSEEING", 32, 2.5, "Lift to the top floor for the city-wide panorama."],
      ["Louvre Museum Guided Tour", "CULTURE", 45, 3, "Skip-the-line highlights walk through the world's largest museum."],
      ["Seine River Dinner Cruise", "FOOD", 89, 2.5, "Three-course dinner while the monuments drift past."],
      ["Montmartre Walking Tour", "SIGHTSEEING", 25, 2, "Sacré-Cœur, artist squares and the old village lanes."],
      ["Latin Quarter Food Crawl", "FOOD", 75, 3.5, "Cheese, charcuterie and pastry stops with a local guide."],
      ["Musée d'Orsay Entry", "CULTURE", 16, 2.5, "Impressionist masterpieces inside a converted railway station."],
      ["Versailles Day Trip", "CULTURE", 65, 7, "Palace state rooms plus the gardens and Trianon estate."],
      ["Moulin Rouge Show", "NIGHTLIFE", 130, 3, "The classic cabaret revue with a glass of champagne."],
      ["Le Marais Vintage Shopping", "SHOPPING", 20, 3, "Concept stores and vintage racks in the old Jewish quarter."],
      ["Luxembourg Gardens Picnic", "NATURE", 18, 2, "Market picnic under the chestnut trees by the palace."],
    ],
  },
  {
    name: "Rome",
    country: "Italy",
    region: "Europe",
    costIndex: 72,
    popularity: 95,
    description: "Three thousand years of city stacked on top of itself.",
    activities: [
      ["Colosseum & Roman Forum", "CULTURE", 38, 3, "Arena floor access and the ruins of the imperial forum."],
      ["Vatican Museums & Sistine Chapel", "CULTURE", 42, 3.5, "Early-entry route to Michelangelo's ceiling."],
      ["Trastevere Food Tour", "FOOD", 78, 3.5, "Supplì, carbonara and tiramisù across the river."],
      ["Pantheon & Piazza Navona Walk", "SIGHTSEEING", 0, 1.5, "Free self-guided loop through the baroque centre."],
      ["Borghese Gallery Entry", "CULTURE", 25, 2, "Bernini sculpture and Caravaggio in a garden villa."],
      ["Pasta-Making Class", "FOOD", 68, 3, "Hand-roll cacio e pepe and tonnarelli with a Roman nonna."],
      ["Appian Way Bike Ride", "ADVENTURE", 35, 4, "Cycle the original Roman road past catacombs and aqueducts."],
      ["Testaccio Market Morning", "FOOD", 15, 2, "The city's best sandwich counter and produce stalls."],
      ["Campo de' Fiori Wine Bars", "NIGHTLIFE", 45, 3, "Enoteca hopping around the evening square."],
      ["Villa Doria Pamphili Run", "NATURE", 0, 1.5, "Rome's largest park, pine-shaded and locals-only."],
    ],
  },
  {
    name: "Barcelona",
    country: "Spain",
    region: "Europe",
    costIndex: 64,
    popularity: 92,
    description: "Gaudí, Gothic lanes and a beach at the end of the metro line.",
    activities: [
      ["Sagrada Família with Tower", "SIGHTSEEING", 47, 2, "Gaudí's basilica plus a lift up the Nativity tower."],
      ["Park Güell Entry", "SIGHTSEEING", 18, 2, "Mosaic terrace and the hillside view over the city."],
      ["Tapas & Vermouth Crawl", "FOOD", 62, 3, "Five bars through El Born and the Gothic Quarter."],
      ["Casa Batlló Audio Tour", "CULTURE", 35, 1.5, "The dragon-scale house with an augmented-reality guide."],
      ["Montjuïc Cable Car & Castle", "SIGHTSEEING", 22, 3, "Harbour views from the cable car and the old fortress."],
      ["Barceloneta Beach Day", "NATURE", 0, 4, "Swim, chiringuito lunch and a walk along the boardwalk."],
      ["Flamenco at Palau Dalmases", "NIGHTLIFE", 30, 1.5, "Intimate tablao in a 17th-century palace courtyard."],
      ["La Boqueria Market Tasting", "FOOD", 28, 1.5, "Jamón, seafood and fruit juice along the Rambla."],
      ["Costa Brava Kayak Trip", "ADVENTURE", 95, 8, "Sea caves and cove swimming an hour up the coast."],
      ["Passeig de Gràcia Shopping", "SHOPPING", 25, 2.5, "Modernista facades and the city's flagship stores."],
    ],
  },
  {
    name: "Amsterdam",
    country: "Netherlands",
    region: "Europe",
    costIndex: 78,
    popularity: 88,
    description: "Canal rings, bike lanes and small museums that punch far above their size.",
    activities: [
      ["Canal Cruise", "SIGHTSEEING", 22, 1.5, "Open-boat loop through the 17th-century canal belt."],
      ["Rijksmuseum Entry", "CULTURE", 25, 3, "Rembrandt, Vermeer and the Dutch Golden Age."],
      ["Anne Frank House", "CULTURE", 16, 1.5, "Timed-entry visit to the secret annex."],
      ["Van Gogh Museum", "CULTURE", 22, 2.5, "The largest collection of his work anywhere."],
      ["Jordaan Bike Tour", "ADVENTURE", 32, 3, "Guided ride through courtyards and canal-side streets."],
      ["Cheese & Genever Tasting", "FOOD", 45, 2, "Aged goudas paired with Dutch gin in a proefokaal."],
      ["Vondelpark Afternoon", "NATURE", 0, 2, "The city's green lung, best on a rented bike."],
      ["Albert Cuyp Market", "SHOPPING", 15, 2, "Street market for stroopwafels and cheap Dutch snacks."],
      ["Zaanse Schans Windmills", "SIGHTSEEING", 38, 5, "Working windmills and clog workshops outside the city."],
      ["Brown Café Evening", "NIGHTLIFE", 35, 2.5, "Beer and bitterballen in a centuries-old pub."],
    ],
  },
  {
    name: "Prague",
    country: "Czechia",
    region: "Europe",
    costIndex: 45,
    popularity: 85,
    description: "A gothic skyline that survived the century intact, on a beer budget.",
    activities: [
      ["Prague Castle Complex", "CULTURE", 20, 3, "St Vitus Cathedral, the old palace and Golden Lane."],
      ["Charles Bridge Sunrise Walk", "SIGHTSEEING", 0, 1, "The bridge statues before the crowds arrive."],
      ["Old Town & Astronomical Clock", "SIGHTSEEING", 12, 2, "Tower climb and the hourly clock performance."],
      ["Czech Beer Tasting Tour", "FOOD", 40, 3, "Four pubs, four styles, one very patient guide."],
      ["Vltava River Paddle Boat", "ADVENTURE", 15, 1.5, "Pedal boat between the bridges at golden hour."],
      ["Jewish Quarter Museum Pass", "CULTURE", 25, 2.5, "Six synagogues and the old cemetery on one ticket."],
      ["Petřín Hill & Lookout Tower", "NATURE", 10, 2.5, "Funicular up and a small Eiffel over the rooftops."],
      ["Black Light Theatre Show", "NIGHTLIFE", 28, 1.5, "Prague's signature surreal stage tradition."],
      ["Vinohrady Café Morning", "FOOD", 12, 1.5, "Third-wave coffee in the residential art-nouveau quarter."],
      ["Havelská Market Browsing", "SHOPPING", 10, 1, "Wooden toys, garnets and produce in the old market."],
    ],
  },
  {
    name: "Lisbon",
    country: "Portugal",
    region: "Europe",
    costIndex: 52,
    popularity: 87,
    description: "Tiled hills, Atlantic light and the best pastry in Europe.",
    activities: [
      ["Tram 28 Ride", "SIGHTSEEING", 4, 1, "The classic yellow tram through Alfama's hills."],
      ["Belém Tower & Jerónimos", "CULTURE", 22, 3, "Manueline monuments from the age of discovery."],
      ["Pastéis de Belém Tasting", "FOOD", 8, 0.5, "The original custard tarts, still warm."],
      ["Alfama Fado Night", "NIGHTLIFE", 55, 2.5, "Dinner and live fado in a tiny tiled room."],
      ["Sintra Day Trip", "SIGHTSEEING", 48, 7, "Pena Palace and the Moorish castle in the hills."],
      ["LX Factory Browsing", "SHOPPING", 15, 2, "Design shops and bookstores in a converted mill."],
      ["Time Out Market Lunch", "FOOD", 30, 1.5, "Twenty of the city's best chefs under one roof."],
      ["Cascais Coastal Cycle", "ADVENTURE", 25, 4, "Flat seafront path along the Atlantic to Guincho."],
      ["Miradouro Sunset Circuit", "NATURE", 0, 2, "Three viewpoints, one bottle of vinho verde."],
      ["Surf Lesson at Costa da Caparica", "ADVENTURE", 55, 3, "Beginner beach break twenty minutes from the city."],
    ],
  },
  {
    name: "Santorini",
    country: "Greece",
    region: "Europe",
    costIndex: 76,
    popularity: 90,
    description: "A drowned volcano rim with white villages clinging to the edge.",
    activities: [
      ["Oia Sunset Viewpoint", "SIGHTSEEING", 0, 2, "The famous caldera sunset — arrive ninety minutes early."],
      ["Caldera Catamaran Cruise", "ADVENTURE", 120, 5, "Hot springs, red beach and dinner on deck."],
      ["Akrotiri Archaeological Site", "CULTURE", 15, 1.5, "The Bronze Age town buried by the eruption."],
      ["Santorini Wine Tasting", "FOOD", 65, 3, "Assyrtiko from vines coiled against the wind."],
      ["Fira to Oia Caldera Hike", "NATURE", 0, 4, "Ten kilometres along the rim between the villages."],
      ["Red Beach Swim", "NATURE", 0, 2.5, "Volcanic cliffs over dark red sand."],
      ["Greek Cooking Class", "FOOD", 85, 3.5, "Tomatokeftedes and fava with a caldera view."],
      ["Ammoudi Bay Seafood Dinner", "FOOD", 60, 2, "Grilled octopus at the water's edge below Oia."],
      ["Sailing Sunset Cruise", "ADVENTURE", 135, 5, "Traditional rig around the volcanic islets."],
      ["Local Art & Jewellery Shops", "SHOPPING", 30, 1.5, "Cycladic pieces along the Fira main street."],
    ],
  },
  {
    name: "Reykjavik",
    country: "Iceland",
    region: "Europe",
    costIndex: 94,
    popularity: 82,
    description: "A small capital used as base camp for a very large landscape.",
    activities: [
      ["Blue Lagoon Entry", "NATURE", 85, 3, "Geothermal silica bathing in a lava field."],
      ["Golden Circle Tour", "SIGHTSEEING", 110, 8, "Þingvellir rift, Geysir and Gullfoss in one loop."],
      ["Northern Lights Hunt", "ADVENTURE", 75, 4, "Guided night chase away from the city glow."],
      ["Hallgrímskirkja Tower", "SIGHTSEEING", 10, 1, "Lift up the basalt-column church for the rooftop view."],
      ["Glacier Hike on Sólheimajökull", "ADVENTURE", 145, 6, "Crampons and a guide on the outlet glacier."],
      ["Whale Watching from Old Harbour", "NATURE", 95, 3.5, "Minke and humpback in Faxaflói bay."],
      ["Icelandic Seafood Dinner", "FOOD", 75, 2, "Langoustine and arctic char at the harbour."],
      ["Reykjavik Bar Rúntur", "NIGHTLIFE", 60, 3, "The Friday night bar circuit on Laugavegur."],
      ["Laugavegur Design Shops", "SHOPPING", 40, 2, "Wool, ceramics and Icelandic design labels."],
      ["National Museum of Iceland", "CULTURE", 20, 2, "Settlement to independence in one clear timeline."],
    ],
  },

  // ─────────────────────────── Asia ───────────────────────────
  {
    name: "Tokyo",
    country: "Japan",
    region: "Asia",
    costIndex: 74,
    popularity: 97,
    description: "Thirteen cities in a trench coat, all of them running on time.",
    activities: [
      ["Tsukiji Outer Market Breakfast", "FOOD", 25, 2, "Tamagoyaki, uni and knife shops at dawn."],
      ["Senso-ji Temple & Nakamise", "CULTURE", 0, 2, "Asakusa's ancient temple and its approach street."],
      ["TeamLab Digital Art Museum", "CULTURE", 32, 3, "Room-scale interactive light installations."],
      ["Shibuya Crossing & Sky", "SIGHTSEEING", 20, 1.5, "The scramble from street level then from 229 metres up."],
      ["Sushi Omakase Counter", "FOOD", 120, 2, "Chef's course at an eight-seat counter."],
      ["Mount Fuji & Hakone Day Trip", "NATURE", 130, 10, "Lake Ashi, the ropeway and the mountain on a clear day."],
      ["Golden Gai Bar Hopping", "NIGHTLIFE", 55, 3, "Six-seat bars packed into a Shinjuku alley grid."],
      ["Akihabara Electronics Hunt", "SHOPPING", 30, 2.5, "Multi-storey retro games and component shops."],
      ["Shinjuku Gyoen Garden", "NATURE", 5, 2, "Japanese, English and French gardens in one park."],
      ["Sumo Morning Practice", "CULTURE", 60, 2, "Watch a training stable's morning keiko session."],
    ],
  },
  {
    name: "Kyoto",
    country: "Japan",
    region: "Asia",
    costIndex: 68,
    popularity: 93,
    description: "Sixteen hundred temples and the slowest, best mornings in Japan.",
    activities: [
      ["Fushimi Inari Shrine Hike", "SIGHTSEEING", 0, 3, "Ten thousand vermilion gates up the mountainside."],
      ["Arashiyama Bamboo Grove", "NATURE", 0, 1.5, "The bamboo path, best entered before seven."],
      ["Kinkaku-ji Golden Pavilion", "SIGHTSEEING", 6, 1.5, "Gold leaf reflected in the mirror pond."],
      ["Tea Ceremony in Gion", "CULTURE", 55, 1.5, "Full matcha ceremony in a machiya townhouse."],
      ["Nishiki Market Food Walk", "FOOD", 35, 2, "Kyoto's kitchen — pickles, yuba and tofu doughnuts."],
      ["Kaiseki Dinner", "FOOD", 150, 2.5, "Multi-course seasonal tasting menu."],
      ["Philosopher's Path Walk", "NATURE", 0, 2, "Canal-side stroll between Ginkaku-ji and Nanzen-ji."],
      ["Kimono Rental & Photo Walk", "CULTURE", 65, 4, "Full dressing plus a walk through Higashiyama."],
      ["Nara Deer Park Day Trip", "NATURE", 30, 6, "Todai-ji's great buddha and eight hundred bowing deer."],
      ["Pontocho Alley Evening", "NIGHTLIFE", 70, 2.5, "Lantern-lit riverside alley of tiny restaurants."],
    ],
  },
  {
    name: "Bangkok",
    country: "Thailand",
    region: "Asia",
    costIndex: 34,
    popularity: 91,
    description: "Street food, gold temples and a river that is still the main road.",
    activities: [
      ["Grand Palace & Wat Phra Kaew", "CULTURE", 16, 2.5, "The royal complex and the Emerald Buddha."],
      ["Chao Phraya Longtail Boat", "ADVENTURE", 25, 2, "Canal backwaters and the riverside temples."],
      ["Street Food Tour in Chinatown", "FOOD", 32, 3.5, "Yaowarat Road after dark, seven stops."],
      ["Wat Arun at Sunset", "SIGHTSEEING", 3, 1.5, "Porcelain-tiled spire across the river."],
      ["Thai Cooking Class", "FOOD", 45, 4, "Market shop then four dishes from scratch."],
      ["Chatuchak Weekend Market", "SHOPPING", 15, 3, "Fifteen thousand stalls, take the air-conditioned route."],
      ["Traditional Thai Massage", "OTHER", 18, 1.5, "Two hours of stretching at Wat Pho's school."],
      ["Rooftop Sky Bar Evening", "NIGHTLIFE", 40, 2, "Sixty floors up over the river bend."],
      ["Ayutthaya Ruins Day Trip", "CULTURE", 55, 8, "The former capital's brick temples and buddha head."],
      ["Lumpini Park Morning", "NATURE", 0, 1.5, "Tai chi, monitor lizards and a paddle boat."],
    ],
  },
  {
    name: "Ubud",
    country: "Indonesia",
    region: "Asia",
    costIndex: 30,
    popularity: 86,
    description: "Rice terraces, temples and the island's creative interior.",
    activities: [
      ["Tegallalang Rice Terraces", "NATURE", 5, 2, "Stepped paddies and the jungle swing viewpoints."],
      ["Sacred Monkey Forest", "NATURE", 6, 1.5, "Temple ruins in a banyan forest full of macaques."],
      ["Balinese Cooking Class", "FOOD", 40, 4, "Market visit then base gede, satay and lawar."],
      ["Mount Batur Sunrise Trek", "ADVENTURE", 65, 7, "Two-hour night climb for sunrise over the caldera."],
      ["Tirta Empul Water Temple", "CULTURE", 12, 2, "Purification springs with a local ceremony guide."],
      ["Yoga & Meditation Session", "OTHER", 15, 1.5, "Open-air shala class in the rice fields."],
      ["Ubud Art Market", "SHOPPING", 20, 1.5, "Batik, carvings and rattan bags — haggling expected."],
      ["Campuhan Ridge Walk", "NATURE", 0, 2, "Easy ridge path between two rivers at dawn."],
      ["Traditional Balinese Massage", "OTHER", 18, 1.5, "Warm oil and frangipani in a garden spa."],
      ["Legong Dance Performance", "CULTURE", 12, 1.5, "Gamelan and masked dance at the palace."],
    ],
  },
  {
    name: "Singapore",
    country: "Singapore",
    region: "Asia",
    costIndex: 80,
    popularity: 89,
    description: "A tropical city-state that treats urban planning as an art form.",
    activities: [
      ["Gardens by the Bay", "NATURE", 28, 3, "Cloud Forest dome and the Supertree light show."],
      ["Marina Bay Sands SkyPark", "SIGHTSEEING", 24, 1.5, "The observation deck on the boat-shaped roof."],
      ["Hawker Centre Food Crawl", "FOOD", 20, 2.5, "Chicken rice, laksa and chilli crab for pocket change."],
      ["Sentosa Island Day", "ADVENTURE", 60, 6, "Cable car, beaches and the luge track."],
      ["Singapore Zoo & Night Safari", "NATURE", 65, 5, "Open-concept enclosures, best done after dark."],
      ["Kampong Glam & Little India Walk", "CULTURE", 0, 2.5, "Shophouse streets, mosques and spice shops."],
      ["Singapore Sling at Raffles", "NIGHTLIFE", 35, 1.5, "The original cocktail in the Long Bar."],
      ["Orchard Road Shopping", "SHOPPING", 40, 3, "Two kilometres of air-conditioned malls."],
      ["National Gallery Singapore", "CULTURE", 20, 2.5, "Southeast Asian art in the old Supreme Court."],
      ["Pulau Ubin Bike Ride", "ADVENTURE", 20, 5, "Bumboat to the last kampong island and a mountain-bike loop."],
    ],
  },
  {
    name: "Seoul",
    country: "South Korea",
    region: "Asia",
    costIndex: 62,
    popularity: 88,
    description: "Palaces, mountains and a nightlife that genuinely does not stop.",
    activities: [
      ["Gyeongbokgung Palace", "CULTURE", 4, 2.5, "Guard-changing ceremony and the throne hall."],
      ["Bukchon Hanok Village", "SIGHTSEEING", 0, 2, "Six hundred traditional houses on a hillside grid."],
      ["Korean BBQ Dinner", "FOOD", 35, 2, "Samgyeopsal and soju at a charcoal table."],
      ["Gwangjang Market Food Tour", "FOOD", 25, 2, "Bindaetteok, mayak gimbap and live octopus if you dare."],
      ["Bukhansan Day Hike", "ADVENTURE", 0, 5, "Granite peaks inside the city boundary."],
      ["N Seoul Tower Cable Car", "SIGHTSEEING", 18, 2, "Namsan ridge and the city laid out below."],
      ["Hongdae Nightlife Circuit", "NIGHTLIFE", 45, 4, "Live music, board-game cafés and street busking."],
      ["Myeongdong Skincare Shopping", "SHOPPING", 50, 2, "K-beauty flagships and a lot of free samples."],
      ["DMZ Half-Day Tour", "CULTURE", 70, 6, "The Joint Security Area and the third infiltration tunnel."],
      ["Jjimjilbang Spa Visit", "OTHER", 12, 3, "Bathhouse, sauna rooms and a nap on a heated floor."],
    ],
  },
  {
    name: "Hanoi",
    country: "Vietnam",
    region: "Asia",
    costIndex: 22,
    popularity: 84,
    description: "French shophouses, motorbike rivers and the cheapest great food anywhere.",
    activities: [
      ["Old Quarter Street Food Walk", "FOOD", 18, 3, "Phở, bún chả and egg coffee across thirty-six streets."],
      ["Hoan Kiem Lake & Ngoc Son", "SIGHTSEEING", 2, 1.5, "The red bridge and the turtle temple at dawn."],
      ["Ha Long Bay Day Cruise", "ADVENTURE", 85, 12, "Limestone karsts, a cave and kayaking in the bay."],
      ["Temple of Literature", "CULTURE", 3, 1.5, "Vietnam's first university, founded in 1070."],
      ["Water Puppet Theatre", "CULTURE", 8, 1, "Thousand-year-old puppetry performed over a pool."],
      ["Vietnamese Cooking Class", "FOOD", 35, 4, "Market run then spring rolls and caramel pork."],
      ["Train Street Coffee", "SIGHTSEEING", 4, 1, "Cà phê sữa đá a metre from the passing train."],
      ["Ho Chi Minh Mausoleum Complex", "CULTURE", 2, 2, "The mausoleum, stilt house and one-pillar pagoda."],
      ["Dong Xuan Market", "SHOPPING", 12, 1.5, "Wholesale market for fabric, silk and lacquerware."],
      ["Bia Hoi Corner Evening", "NIGHTLIFE", 10, 2, "Fresh draught beer on a plastic stool for a dollar."],
    ],
  },
  {
    name: "Jaipur",
    country: "India",
    region: "Asia",
    costIndex: 26,
    popularity: 83,
    description: "The pink city of Rajasthan — forts above, bazaars below.",
    activities: [
      ["Amber Fort & Sheesh Mahal", "CULTURE", 8, 3, "Hilltop fort and its mirror-work hall of glass."],
      ["Hawa Mahal Facade & Museum", "SIGHTSEEING", 3, 1, "The 953-window palace of the winds."],
      ["City Palace & Chandra Mahal", "CULTURE", 10, 2.5, "Royal courtyards, textiles and the armoury."],
      ["Jantar Mantar Observatory", "CULTURE", 3, 1.5, "Eighteenth-century stone astronomical instruments."],
      ["Rajasthani Thali Dinner", "FOOD", 9, 1.5, "Dal baati churma and gatte ki sabzi, unlimited refills."],
      ["Bazaar Textile Shopping", "SHOPPING", 25, 2.5, "Block prints and bandhani in Johari and Bapu bazaars."],
      ["Nahargarh Fort Sunset", "SIGHTSEEING", 3, 2, "The whole city grid glowing from the ridge."],
      ["Block Printing Workshop", "CULTURE", 20, 2, "Carve and print your own scarf in Sanganer."],
      ["Hot Air Balloon over Amer", "ADVENTURE", 130, 3, "Sunrise flight over the forts and stepwells."],
      ["Chokhi Dhani Village Evening", "NIGHTLIFE", 22, 3.5, "Folk dance, camel rides and a village-style feast."],
    ],
  },

  // ─────────────────────── Middle East ───────────────────────
  {
    name: "Dubai",
    country: "United Arab Emirates",
    region: "Middle East",
    costIndex: 79,
    popularity: 89,
    description: "Desert, superlatives and a very good old town people forget about.",
    activities: [
      ["Burj Khalifa Level 124", "SIGHTSEEING", 45, 2, "The world's tallest building at sunset."],
      ["Desert Safari with Dinner", "ADVENTURE", 75, 6, "Dune bashing, camels and a camp barbecue."],
      ["Dubai Mall & Fountain Show", "SHOPPING", 0, 3, "Twelve hundred shops and the hourly fountain."],
      ["Old Dubai Abra & Souks", "CULTURE", 5, 2.5, "Creek crossing to the gold and spice souks."],
      ["Dubai Marina Yacht Cruise", "ADVENTURE", 60, 2, "Skyline loop past the Palm and Atlantis."],
      ["Emirati Cuisine Dinner", "FOOD", 45, 2, "Machboos and luqaimat in Al Fahidi."],
      ["Jumeirah Beach Day", "NATURE", 0, 4, "Open public beach with the Burj Al Arab in frame."],
      ["Museum of the Future", "CULTURE", 40, 2.5, "Immersive exhibits inside the calligraphy torus."],
      ["Dubai Frame", "SIGHTSEEING", 14, 1.5, "Glass walkway framing old and new city."],
      ["Global Village Evening", "NIGHTLIFE", 5, 3, "Pavilions, street food and shows from eighty countries."],
    ],
  },
  {
    name: "Istanbul",
    country: "Türkiye",
    region: "Middle East",
    costIndex: 40,
    popularity: 90,
    description: "Two continents, one city, and every empire that mattered.",
    activities: [
      ["Hagia Sophia", "CULTURE", 25, 1.5, "Byzantine cathedral, Ottoman mosque, still standing."],
      ["Blue Mosque & Hippodrome", "CULTURE", 0, 1.5, "Iznik tiles and the old chariot-racing square."],
      ["Topkapi Palace & Harem", "CULTURE", 30, 3, "Ottoman court, treasury and the Bosphorus terrace."],
      ["Bosphorus Ferry Cruise", "SIGHTSEEING", 12, 2, "Public ferry between Europe and Asia."],
      ["Grand Bazaar Shopping", "SHOPPING", 30, 2.5, "Four thousand shops under vaulted ceilings."],
      ["Turkish Hammam", "OTHER", 45, 1.5, "Marble slab, scrub and foam in a 16th-century bath."],
      ["Meze & Rakı Dinner in Beyoğlu", "FOOD", 40, 2.5, "Meyhane table of small plates and anise spirit."],
      ["Basilica Cistern", "SIGHTSEEING", 20, 1, "Sunken forest of columns and the Medusa heads."],
      ["Kadıköy Food Tour", "FOOD", 38, 3, "The Asian side's market street, seven tastings."],
      ["Balat & Fener Walk", "SIGHTSEEING", 0, 2, "Coloured houses and the old Greek and Jewish quarters."],
    ],
  },

  // ─────────────────────────── Africa ───────────────────────────
  {
    name: "Marrakech",
    country: "Morocco",
    region: "Africa",
    costIndex: 33,
    popularity: 85,
    description: "A walled medina that runs on tea, argument and afternoon light.",
    activities: [
      ["Jemaa el-Fnaa at Dusk", "SIGHTSEEING", 0, 2, "Snake charmers, food carts and storytellers in the main square."],
      ["Medina Souk Tour", "SHOPPING", 20, 3, "Leather, lanterns and spices with a guide who knows the prices."],
      ["Bahia Palace", "CULTURE", 8, 1.5, "Painted cedar ceilings and courtyard gardens."],
      ["Jardin Majorelle & YSL Museum", "NATURE", 25, 2, "Cobalt-blue garden and the designer's collection."],
      ["Moroccan Cooking Class", "FOOD", 45, 4, "Souk shopping then tagine and preserved lemon."],
      ["Traditional Hammam & Scrub", "OTHER", 30, 1.5, "Black soap, gommage and mint tea after."],
      ["Atlas Mountains Day Trip", "ADVENTURE", 60, 8, "Berber villages and a waterfall hike in Imlil."],
      ["Agafay Desert Camel Sunset", "ADVENTURE", 55, 4, "Stone desert ride and dinner under lanterns."],
      ["Rooftop Mint Tea", "FOOD", 6, 1, "Koutoubia minaret view over the medina rooftops."],
      ["Le Jardin Secret", "NATURE", 9, 1, "Restored riad garden hidden in the old town."],
    ],
  },
  {
    name: "Cape Town",
    country: "South Africa",
    region: "Africa",
    costIndex: 42,
    popularity: 87,
    description: "A mountain, two oceans and wine country forty minutes away.",
    activities: [
      ["Table Mountain Cableway", "NATURE", 25, 3, "Rotating car to the flat summit and its trails."],
      ["Cape Point & Chapman's Peak", "SIGHTSEEING", 65, 8, "Coastal drive to the peninsula's tip."],
      ["Boulders Beach Penguins", "NATURE", 10, 1.5, "Boardwalk over an African penguin colony."],
      ["Robben Island Tour", "CULTURE", 35, 4, "Ferry and prison tour led by a former inmate."],
      ["Stellenbosch Wine Tasting", "FOOD", 70, 7, "Three estates in the Cape Winelands."],
      ["Bo-Kaap Walking Tour", "CULTURE", 20, 2, "Coloured houses and Cape Malay history."],
      ["Lion's Head Sunrise Hike", "ADVENTURE", 0, 3, "Spiral trail with chains near the top."],
      ["V&A Waterfront Market", "SHOPPING", 25, 2.5, "Craft market, food hall and harbour seals."],
      ["Shark Cage Diving", "ADVENTURE", 160, 9, "Gansbaai day trip with the operators who do it properly."],
      ["Kirstenbosch Gardens", "NATURE", 12, 2.5, "Fynbos gardens on the mountain's back slope."],
    ],
  },
  {
    name: "Cairo",
    country: "Egypt",
    region: "Africa",
    costIndex: 25,
    popularity: 84,
    description: "The last standing ancient wonder, on the edge of a 22-million-person city.",
    activities: [
      ["Pyramids of Giza & Sphinx", "SIGHTSEEING", 22, 4, "The plateau, the Sphinx and the inside of Khufu."],
      ["Grand Egyptian Museum", "CULTURE", 30, 4, "Tutankhamun's complete collection in one hall."],
      ["Khan el-Khalili Bazaar", "SHOPPING", 15, 2.5, "Medieval market for brass, glass and perfume oils."],
      ["Nile Felucca Sunset Sail", "ADVENTURE", 20, 1.5, "Traditional sailboat with no engine and no hurry."],
      ["Islamic Cairo Walk", "CULTURE", 18, 3, "Sultan Hassan, Al-Azhar and the old city gates."],
      ["Coptic Cairo & Hanging Church", "CULTURE", 5, 2, "Early Christian Egypt in the Babylon fortress."],
      ["Saqqara & Memphis Trip", "SIGHTSEEING", 40, 5, "The step pyramid and the older necropolis."],
      ["Egyptian Street Food Tour", "FOOD", 15, 2.5, "Koshari, ful and taameya across downtown."],
      ["Al-Azhar Park Evening", "NATURE", 3, 2, "Landscaped hill with the citadel skyline behind."],
      ["Sound & Light Show at Giza", "NIGHTLIFE", 25, 1.5, "The pyramids narrated and lit after dark."],
    ],
  },
  {
    name: "Zanzibar City",
    country: "Tanzania",
    region: "Africa",
    costIndex: 31,
    popularity: 78,
    description: "Swahili coast trading town with reef water twenty minutes north.",
    activities: [
      ["Stone Town Walking Tour", "CULTURE", 20, 2.5, "Carved doors, the old fort and the slave market memorial."],
      ["Spice Farm Tour", "NATURE", 25, 3.5, "Clove, vanilla and nutmeg with a tasting lunch."],
      ["Nakupenda Sandbank Snorkel", "ADVENTURE", 45, 6, "Boat to a tidal sandbar with reef snorkelling."],
      ["Forodhani Night Market", "FOOD", 12, 1.5, "Grilled seafood and Zanzibar pizza on the seafront."],
      ["Prison Island Giant Tortoises", "NATURE", 30, 3, "Century-old Aldabra tortoises and a coral beach."],
      ["Jozani Forest Red Colobus", "NATURE", 18, 2.5, "Endemic monkeys and a mangrove boardwalk."],
      ["Nungwi Beach Day", "NATURE", 15, 5, "White sand and dhow builders on the north tip."],
      ["Sunset Dhow Cruise", "ADVENTURE", 35, 2, "Traditional sail with the Stone Town skyline behind."],
      ["Swahili Cooking Class", "FOOD", 30, 3, "Coconut curry, pilau and chapati from scratch."],
      ["Darajani Market", "SHOPPING", 8, 1.5, "Spices, kanga cloth and the fish auction."],
    ],
  },

  // ─────────────────────── North America ───────────────────────
  {
    name: "New York City",
    country: "United States",
    region: "North America",
    costIndex: 92,
    popularity: 96,
    description: "The city that made the density argument and won it.",
    activities: [
      ["Statue of Liberty & Ellis Island", "SIGHTSEEING", 25, 4, "Ferry, pedestal access and the immigration museum."],
      ["Metropolitan Museum of Art", "CULTURE", 30, 3.5, "Two million works — pick three wings and commit."],
      ["Central Park Bike Loop", "NATURE", 25, 2.5, "Ten kilometres of car-free park drive."],
      ["Broadway Show", "NIGHTLIFE", 140, 3, "Orchestra seat at a current-run musical."],
      ["Top of the Rock Observation", "SIGHTSEEING", 40, 1.5, "The Empire State in your photo, not under your feet."],
      ["Brooklyn Bridge Walk & DUMBO", "SIGHTSEEING", 0, 2, "Cross at sunrise then coffee under the bridge."],
      ["Greenwich Village Food Tour", "FOOD", 85, 3, "Pizza, bagels and Italian delis with a guide."],
      ["The High Line & Chelsea Market", "NATURE", 10, 2.5, "Elevated rail-park then the food hall below."],
      ["9/11 Memorial & Museum", "CULTURE", 33, 2.5, "The reflecting pools and the museum beneath."],
      ["SoHo & Fifth Avenue Shopping", "SHOPPING", 60, 3, "Cast-iron district boutiques and the flagship strip."],
    ],
  },
  {
    name: "San Francisco",
    country: "United States",
    region: "North America",
    costIndex: 88,
    popularity: 86,
    description: "Fog, hills and the most walkable seven miles in America.",
    activities: [
      ["Golden Gate Bridge Bike Ride", "ADVENTURE", 45, 4, "Ride the span to Sausalito and ferry back."],
      ["Alcatraz Island Tour", "CULTURE", 47, 3.5, "Ferry and the cellhouse audio tour."],
      ["Cable Car Ride", "SIGHTSEEING", 8, 1, "Powell-Hyde line over the hill to the bay."],
      ["Mission District Burritos & Murals", "FOOD", 25, 2.5, "Taquería crawl and the Clarion Alley murals."],
      ["Muir Woods Redwoods", "NATURE", 55, 5, "Old-growth coast redwoods across the bridge."],
      ["Ferry Building Marketplace", "FOOD", 35, 2, "Oysters, cheese and the Saturday farmers market."],
      ["Chinatown Walking Tour", "CULTURE", 30, 2, "The oldest Chinatown in North America."],
      ["Napa Valley Wine Day Trip", "FOOD", 160, 9, "Three tastings and lunch in the valley."],
      ["Lands End Coastal Trail", "NATURE", 0, 2.5, "Cliff path with the bridge appearing out of the fog."],
      ["Haight-Ashbury Record Shops", "SHOPPING", 30, 2, "Vinyl and vintage in the old counterculture blocks."],
    ],
  },
  {
    name: "Mexico City",
    country: "Mexico",
    region: "North America",
    costIndex: 38,
    popularity: 85,
    description: "An Aztec capital under a colonial capital under a very good restaurant scene.",
    activities: [
      ["Teotihuacán Pyramids", "SIGHTSEEING", 40, 6, "Avenue of the Dead and the Sun and Moon pyramids."],
      ["Frida Kahlo Museum", "CULTURE", 18, 2, "The Blue House in Coyoacán, book well ahead."],
      ["Centro Histórico Walk", "SIGHTSEEING", 0, 2.5, "Zócalo, cathedral and the Templo Mayor ruins."],
      ["Street Taco Tour", "FOOD", 30, 3, "Al pastor, suadero and barbacoa across four stands."],
      ["Xochimilco Trajinera Boats", "ADVENTURE", 35, 4, "Painted boats, mariachi and floating gardens."],
      ["Museo Nacional de Antropología", "CULTURE", 6, 3.5, "The Aztec sun stone and the best pre-Hispanic collection."],
      ["Lucha Libre Night", "NIGHTLIFE", 25, 3, "Masked wrestling at Arena México."],
      ["Roma & Condesa Café Crawl", "FOOD", 22, 2.5, "Art-deco streets and third-wave coffee."],
      ["Chapultepec Park & Castle", "NATURE", 8, 3, "City forest and the hilltop imperial castle."],
      ["Mercado de la Ciudadela", "SHOPPING", 25, 2, "Folk art and crafts from every Mexican state."],
    ],
  },
  {
    name: "Vancouver",
    country: "Canada",
    region: "North America",
    costIndex: 71,
    popularity: 80,
    description: "Rainforest, ocean and ski runs inside the same commute.",
    activities: [
      ["Stanley Park Seawall Cycle", "NATURE", 20, 3, "Nine kilometres of waterfront around the peninsula."],
      ["Capilano Suspension Bridge", "ADVENTURE", 50, 3, "Canopy walkways and a cliff-edge platform."],
      ["Granville Island Public Market", "FOOD", 30, 2.5, "Food hall, artisan studios and a ferry across False Creek."],
      ["Grouse Mountain Skyride", "NATURE", 60, 4, "Gondola to alpine trails and the grizzly refuge."],
      ["Whale Watching Tour", "NATURE", 110, 4, "Orca and humpback in the Salish Sea."],
      ["Gastown & Steam Clock", "SIGHTSEEING", 0, 1.5, "Cobbled streets and the whistling clock."],
      ["Sushi & Izakaya Dinner", "FOOD", 45, 2, "The best Japanese food outside Japan, locals will insist."],
      ["Sea-to-Sky & Squamish Trip", "ADVENTURE", 90, 8, "Coastal highway, gondola and Shannon Falls."],
      ["Museum of Anthropology", "CULTURE", 18, 2.5, "First Nations houseposts and totem collection."],
      ["Kitsilano Beach Sunset", "NATURE", 0, 2, "City skyline across the water with the mountains behind."],
    ],
  },

  // ─────────────────────── South America ───────────────────────
  {
    name: "Rio de Janeiro",
    country: "Brazil",
    region: "South America",
    costIndex: 44,
    popularity: 88,
    description: "Granite peaks dropping straight into the beach, and a soundtrack.",
    activities: [
      ["Christ the Redeemer", "SIGHTSEEING", 30, 3, "Cog train up Corcovado to the statue."],
      ["Sugarloaf Cable Car", "SIGHTSEEING", 25, 2.5, "Two-stage cable car for the bay at sunset."],
      ["Copacabana & Ipanema Beach Day", "NATURE", 0, 4, "Beach chairs, coconut water and futevôlei."],
      ["Favela Walking Tour", "CULTURE", 35, 3, "Community-led tour of Rocinha or Vidigal."],
      ["Samba Night in Lapa", "NIGHTLIFE", 30, 4, "Live roda de samba under the aqueduct arches."],
      ["Tijuca Forest Hike", "NATURE", 25, 5, "The world's largest urban rainforest and its waterfalls."],
      ["Selarón Steps & Santa Teresa", "SIGHTSEEING", 0, 2, "Tiled staircase then the tram up the hill."],
      ["Feijoada Saturday Lunch", "FOOD", 28, 2.5, "The national black bean stew, done properly."],
      ["Hang Gliding from Pedra Bonita", "ADVENTURE", 160, 3, "Tandem flight landing on São Conrado beach."],
      ["Hippie Fair Ipanema", "SHOPPING", 20, 2, "Sunday craft market for gems and leather."],
    ],
  },
  {
    name: "Buenos Aires",
    country: "Argentina",
    region: "South America",
    costIndex: 36,
    popularity: 82,
    description: "European bones, Latin blood, dinner at eleven.",
    activities: [
      ["Tango Show & Dinner", "NIGHTLIFE", 75, 3.5, "Orchestra, dancers and a steak in San Telmo."],
      ["Recoleta Cemetery", "CULTURE", 12, 1.5, "Marble mausoleums including Evita's."],
      ["La Boca & Caminito", "SIGHTSEEING", 5, 2, "Painted corrugated houses and the Boca stadium."],
      ["Parrilla Steak Dinner", "FOOD", 35, 2.5, "Bife de chorizo, chimichurri and Malbec."],
      ["San Telmo Sunday Market", "SHOPPING", 20, 3, "Antiques, buskers and ten blocks of stalls."],
      ["Palermo Bar Crawl", "NIGHTLIFE", 45, 4, "Speakeasies and craft beer in Palermo Soho."],
      ["Teatro Colón Tour", "CULTURE", 22, 1.5, "Backstage in one of the world's best opera houses."],
      ["Tigre Delta Day Trip", "NATURE", 30, 6, "Train to the delta and a boat through the channels."],
      ["Tango Lesson", "CULTURE", 30, 1.5, "Beginner class before a milonga."],
      ["El Ateneo Bookstore & Cafés", "SHOPPING", 10, 1.5, "A bookshop inside a converted grand theatre."],
    ],
  },
  {
    name: "Cusco",
    country: "Peru",
    region: "South America",
    costIndex: 32,
    popularity: 86,
    description: "Inca capital at 3,400 metres — the gateway to Machu Picchu.",
    activities: [
      ["Machu Picchu Day Trip", "SIGHTSEEING", 220, 14, "Train to Aguas Calientes, bus up, guided circuit."],
      ["Sacred Valley Tour", "CULTURE", 55, 9, "Pisac ruins, Ollantaytambo and the Chinchero weavers."],
      ["Rainbow Mountain Trek", "ADVENTURE", 60, 12, "High-altitude hike to Vinicunca's striped ridge."],
      ["San Pedro Market", "FOOD", 10, 1.5, "Fruit juices, cheeses and the soup counters."],
      ["Sacsayhuamán Ruins", "CULTURE", 22, 2.5, "Megalithic Inca walls above the city."],
      ["Peruvian Cooking Class", "FOOD", 45, 3.5, "Ceviche, lomo saltado and a pisco sour."],
      ["Qorikancha Temple", "CULTURE", 12, 1.5, "Inca sun temple with a monastery built on top."],
      ["Humantay Lake Hike", "NATURE", 50, 10, "Turquoise glacial lake under a snow peak."],
      ["San Blas Artisan Quarter", "SHOPPING", 25, 2, "Alpaca textiles and workshops on the steep lanes."],
      ["Coca Tea & Acclimatisation Walk", "OTHER", 5, 2, "Gentle first-day loop to adjust to the altitude."],
    ],
  },

  // ─────────────────────────── Oceania ───────────────────────────
  {
    name: "Sydney",
    country: "Australia",
    region: "Oceania",
    costIndex: 77,
    popularity: 89,
    description: "A harbour city that treats the outdoors as the main venue.",
    activities: [
      ["Sydney Opera House Tour", "CULTURE", 45, 1.5, "Inside the shells with a backstage guide."],
      ["Harbour Bridge Climb", "ADVENTURE", 190, 3.5, "Summit climb on the arch, 134 metres up."],
      ["Bondi to Coogee Coastal Walk", "NATURE", 0, 3, "Six kilometres of cliff path and beaches."],
      ["Manly Ferry & Beach", "SIGHTSEEING", 12, 4, "The best-value harbour cruise is the commuter ferry."],
      ["Blue Mountains Day Trip", "NATURE", 95, 9, "Three Sisters, Scenic World and a canyon walk."],
      ["Sydney Fish Market Lunch", "FOOD", 35, 1.5, "Sashimi and Balmain bugs straight off the auction floor."],
      ["Taronga Zoo", "NATURE", 50, 4, "Australian wildlife with the skyline behind the enclosures."],
      ["Surf Lesson at Bondi", "ADVENTURE", 75, 2, "Group lesson with board and wetsuit included."],
      ["The Rocks Weekend Market", "SHOPPING", 25, 2, "Craft stalls in the colonial sandstone lanes."],
      ["Darling Harbour Bar Night", "NIGHTLIFE", 55, 3, "Waterfront bars and the Friday fireworks."],
    ],
  },
  {
    name: "Queenstown",
    country: "New Zealand",
    region: "Oceania",
    costIndex: 73,
    popularity: 81,
    description: "The adventure capital, wedged between a lake and the Remarkables.",
    activities: [
      ["Bungy Jump at Kawarau Bridge", "ADVENTURE", 150, 3, "The original commercial bungy, 43 metres."],
      ["Milford Sound Day Trip", "NATURE", 180, 13, "Fiord cruise past Mitre Peak and the waterfalls."],
      ["Skyline Gondola & Luge", "ADVENTURE", 60, 2.5, "Gondola up Bob's Peak then three luge runs."],
      ["Shotover Jet Boat", "ADVENTURE", 110, 1.5, "360-degree spins through the river canyon."],
      ["Lake Wakatipu Cruise", "NATURE", 55, 2, "Steamship TSS Earnslaw across the lake."],
      ["Gibbston Valley Wine Tour", "FOOD", 90, 5, "Pinot noir tastings in the valley of the vines."],
      ["Fergburger & Lakefront Dinner", "FOOD", 20, 1, "The queue is real and it is worth it."],
      ["Ben Lomond Track Hike", "NATURE", 0, 6, "Steep alpine climb for the full 360 over the lake."],
      ["Skydive over the Remarkables", "ADVENTURE", 300, 3, "Tandem jump from 15,000 feet."],
      ["Onsen Hot Pools", "OTHER", 85, 1.5, "Private cedar tubs on a cliff over the Shotover."],
    ],
  },
];

// ─── Photography ────────────────────────────────────────────────────────────
// Unsplash delivery URLs. Every id below was requested and confirmed to return
// 200 before being committed; ImageFallback still catches any that later
// disappear, so a dead id degrades to the gradient rather than a broken image.

const photo = (id: string) =>
  `https://images.unsplash.com/${id}?w=1200&q=80&auto=format&fit=crop`;

/** City name -> hero photo. Applied by prisma/seed.ts. */
export const CITY_PHOTO: Record<string, string> = {
  Paris: photo("photo-1502602898657-3e91760cbb34"),
  Rome: photo("photo-1552832230-c0197dd311b5"),
  Barcelona: photo("photo-1583422409516-2895a77efded"),
  Amsterdam: photo("photo-1534351590666-13e3e96b5017"),
  Prague: photo("photo-1541849546-216549ae216d"),
  Lisbon: photo("photo-1585208798174-6cedd86e019a"),
  Santorini: photo("photo-1570077188670-e3a8d69ac5ff"),
  Reykjavik: photo("photo-1504829857797-ddff29c27927"),
  Tokyo: photo("photo-1540959733332-eab4deabeeaf"),
  Kyoto: photo("photo-1493976040374-85c8e12f0c0e"),
  Bangkok: photo("photo-1508009603885-50cf7c579365"),
  Ubud: photo("photo-1537996194471-e657df975ab4"),
  Singapore: photo("photo-1525625293386-3f8f99389edd"),
  Seoul: photo("photo-1538485399081-7191377e8241"),
  Hanoi: photo("photo-1583417319070-4a69db38a482"),
  Jaipur: photo("photo-1477587458883-47145ed94245"),
  Dubai: photo("photo-1512453979798-5ea266f8880c"),
  Istanbul: photo("photo-1524231757912-21f4fe3a7200"),
  Marrakech: photo("photo-1597212618440-806262de4f6b"),
  "Cape Town": photo("photo-1580060839134-75a5edca2e99"),
  Cairo: photo("photo-1572252009286-268acec5ca0a"),
  "Zanzibar City": photo("photo-1516026672322-bc52d61a55d5"),
  "New York City": photo("photo-1496442226666-8d4d0e62e6e9"),
  "San Francisco": photo("photo-1501594907352-04cda38ebc29"),
  "Mexico City": photo("photo-1518105779142-d975f22f1b0a"),
  Vancouver: photo("photo-1560814304-4f05b62af116"),
  "Rio de Janeiro": photo("photo-1483729558449-99ef09a8c325"),
  "Buenos Aires": photo("photo-1589909202802-8f4aadce1849"),
  Cusco: photo("photo-1526392060635-9d6019884377"),
  Sydney: photo("photo-1506973035872-a4ec16b8e8d9"),
  Queenstown: photo("photo-1589802829985-817e51171b92"),
};

/**
 * One representative photo per activity category. 310 individually-chosen
 * images could not each be verified, so a category image is the honest choice:
 * always on-topic, never confidently wrong about a specific tour.
 */
export const CATEGORY_PHOTO: Record<string, string> = {
  SIGHTSEEING: photo("photo-1476514525535-07fb3b4ae5f1"),
  FOOD: photo("photo-1504674900247-0877df9cc836"),
  ADVENTURE: photo("photo-1533692328991-08159ff19fca"),
  CULTURE: photo("photo-1513151233558-d860c5398176"),
  NIGHTLIFE: photo("photo-1470229722913-7c0e2dbbafd3"),
  SHOPPING: photo("photo-1441986300917-64674bd600d8"),
  NATURE: photo("photo-1441974231531-c6227db76b6e"),
  OTHER: photo("photo-1488646953014-85cb44e25828"),
};
